### ISSUE TITLE
Package TODO

### ISSUE THREAD

**Issue by lgatto** [rformassspectrometry/PSMatch#1]
## Transferred from `MSnbase`
- [X] reading and filtering PSMs: ~`readPSMs()`~ `PSM()` and `filterPsm*()`.
- [X] Fragment peak calculation: `calculateFragments()` and helper functions.
- [X] Amino acids and atomic masses (required for `calculateFragments()`)

## Development
- [x] increase unit testing coverage

## Integration with other packages
- [x] Harmonise variable names between `mzR` and `mzID` (both supported as parsers)
- [ ] Integration with `MSnID`

## New functionality
- [x] Handling and visualisation of identification/inference data: peptide by protein adjacency matrices (see discussions with @SJan1) - see issue #8 

## Add to vignette 
- [x] section about adjacency matrix
- [x] `calculateFragments()` 
- [x] `ConnectedComponents`
